<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\App;
use App\Http\Controllers\RoutesController;
use App\Http\Controllers\ListController;

Route::get('/', [RoutesController::class, 'homePage']);

Route::group(['middleware' => 'auth'], function () {

    // Route to form for user to manually enter a new location
    Route::get('/pages/addLocation/new', [RoutesController::class, 'create']);
    // Route for processing the add location to database request
    Route::post('/pages/addLocation', [RoutesController::class, 'store']);

    // Route to display tourist locations for a city.
    Route::get('/pages/discover/cities', [RoutesController::class, 'discover']);
    // Route to generate list of tourist locations for the city.
    Route::get('/pages/discover', [RoutesController::class, 'discoverCities']);

    Route::get('pages/{name}/reviews', [RoutesController::class, 'showReviews']);


    // Route to show the user's saved locations
    Route::get('/list', [ListController::class, 'showList']);
    // Route for locations already in the database
    Route::get('/list/{name}/add', [ListController::class, 'addToList']);
    // Route to save a location to a user list (locations generated by seeder data)
    Route::post('/list/{name}/save', [ListController::class, 'save']);
    // Route for updated user notes for their saved locations
    Route::put('/list/{name}/update', [ListController::class, 'update']);

    Route::get('/list/{name}/delete', [ListController::class, 'checkDelete']);
    // Route to delete location from user list
    Route::delete('/list/{name}/destroy', [ListController::class, 'destroy']);

    // // Route to page to add locations from cityPlaces function (locations generated from an API call)
    // Route::get('/pages/list/{name}', [RoutesController::class, 'addCityPlaces']);
    // // Route to function that processes adding cityPlaces generated location to Database
    // Route::post('/pages/list/{name}/new', [RoutesController::class, 'addCityPlacesLoc']);
});